name: 浦东张江
description: 生活文档1.0版
url: "http://211.im"
baseurl: /

# addition properties
tecent_group_no: 324597273
douban_group_name: 浦东张江租房
douban_group_link: http://www.douban.com/group/zjhouse/
github_repo_name: 211.im
github_repo_link: https://github.com/Shevckcccc/211.im

#author
author_name: Shevckcccc
author_url: http://weibo.com/karahcccc


# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
highlighter: pygments
